--[[
	Package link auto-generated by Kayak
]]

local PackageIndex = script.Parent._index

local package = PackageIndex["lua-promise"]["promise"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package